[package]
name = "solana-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "solana_core"
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.169"
solana-client = "2.1.7"
solana-sdk = "2.1.7"
rust-client = { git = "https://github.com/kouliang/solana-client.git" }
